$(document).ready(function(){
    $(".openmenu").hide();
    $(".showmenu").click(function(){
        $(".openmenu").show();
    });
    $(".close").click(function(){
        $(".openmenu").hide();
    });
});
